any:
    id:
        displayname: keys.id
        osmwiki: Node
        weight: 300
    name:
        displayname: keys.name
        osmwiki: Key:name
        weight: 1
    kind:
        displayname: keys.kind
        weight: 10
    source:
        displayname: keys.source
        weight: 290
    start_date:
        displayname: keys.start_date
        osmwiki: Key:start_date
        weight: 50
    area:
        displayname: keys.area
        weight: 280
    website:
        displayname: keys.website
        wikipedia: Website
        osmwiki: Key:website
        wikidata: Q35127
        wikiproperty: P856
        weight: 240
    wikipedia:
        displayname: keys.wikipedia
        wikipedia: Wikipedia
        osmwiki: Key:wikipedia
        wikidata: Q52
        weight: 250
    wikidata:
        displayname: keys.wikidata
        wikipedia: Wikidata
        osmwiki: Key:wikidata
        wikidata: Q52
        weight: 255
    image:
        displayname: keys.image
        wikipedia: Image
        osmwiki: Key:image
        wikidata: Q478798
        wikiproperty: P18
        weight: 255
    tourism:
        displayname: keys.tourism.tourism
        weight: 110
        osmwiki: Key:tourism
        values:
            attraction:
                displayname: keys.tourism.attraction
            museum:
                displayname: keys.tourism.museum
    heritage:
        displayname: keys.heritage.heritage
        weight: 115
        wikipedia: Cultural_heritage
        wikidata: Q210272
        osmwiki: Key:heritage
        values:
            1:
                displayname: keys.heritage.1
                wikipedia: World_Heritage_Site
                wikidata: Q9259
            2:
                displayname: keys.heritage.2
            3:
                displayname: keys.heritage.3
            4:
                displayname: keys.heritage.4
    "heritage:operator":
        displayname: keys.heritage:operator.operator
        weight: 117
        wikipedia: Cultural_heritage_management
        wikidata: Q572824
        osmwiki: Key:heritage:operator
        values:
            whc:
                displayname: keys.heritage:operator.whc
                wikipedia: UNESCO
                wikidata: Q7809
            rce:
                displayname: keys.heritage:operator.rce
                wikipedia: Rijksdienst_voor_het_Cultureel_Erfgoed
                wikidata: Q1766396
            Rijksmonuments:
                displayname: keys.heritage:operator.Rijksmonuments
                wikipedia: Rijksmonument
                wikidata: Q916333
    "ref:whc":
        displayname: keys.ref:whc
        weight: 118
    historic:
        displayname: keys.historic.historic
        weight: 100
        osmwiki: Key:historic
        values:
            building:
                displayname: keys.historic.building
                wikipedia: Building
                osmwiki: Tag:historic%3Dbuilding
            monument:
                displayname: keys.historic.monument
                wikipedia: Monument
                wikidata: Q4989906
                osmwiki: Tag:historic%3Dmonument
            city_gate:
                displayname: keys.historic.city_gate
                wikipedia: City_gate
                wikidata: Q82117
                osmwiki: Tag:historic%3Dcity_gate
            monastery:
                displayname: keys.historic.monastery
                wikipedia: Monastery
                wikidata: Q44613
                osmwiki: Tag:historic%3Dmonastery
            fortress:
                displayname: keys.historic.fortress
                wikipedia: Fortification
                wikidata: Q57821
                osmwiki: Tag:historic%3Dfortress
            railway_station:
                displayname: keys.historic.railway_station
                wikipedia: Train_station
                wikidata: Q55488
                osmwiki: Tag:historic%3Drailway_station
            church:
                displayname: keys.historic.church
                wikipedia: Church
                wikidata: Q605315
                osmwiki: Tag:historic%3Dchurch
            castle:
                displayname: keys.historic.castle
                wikipedia: Castle
                wikidata: Q23413
                osmwiki: Tag:historic%3Dcastle
            memorial:
                displayname: keys.historic.memorial
                wikipedia: Memorial
                wikidata: Q5003624
                osmwiki: Tag:historic%3Dmemorial
places:
    kind:
        displayname: keys.kind
        osmwiki: Key:place
        values:
            town:
                originalkey: place
                originalname: town
                displayname: keys.place.town
                wikipedia: Town
                wikidata: Q3957
                osmwiki: Tag:place%3Dtown
    population:
        displayname: keys.population
        wikipedia: Population
        wikidata: Q33829
        wikiproperty: P1082
        osmkey: population
        osmwiki: Key:population
        weight: 30
architecture:
    kind:
        displayname: keys.kind
        weight: 10
        values:
            building:
                originalkey: building
                originalname: yes
                displayname: keys.building.building
                osmwiki: Key:building
            commercial:
                originalkey: building
                originalname: commercial
                displayname: keys.building.commercial
                osmwiki: Tag:building=commercial
            retail:
                originalkey: building
                originalname: commercial
                displayname: keys.building.retail
                osmwiki: Tag:building=retail
            industrial:
                originalkey: building
                originalname: commercial
                displayname: keys.building.industrial
                osmwiki: Tag:building=industrial
            apartments:
                originalkey: building
                originalname: apartments
                displayname: keys.building.apartments
                osmwiki: Tag:building=apartments
            house:
                originalkey: building
                originalname: house
                displayname: keys.building.house
                osmwiki: Tag:building=house
            residential:
                originalkey: building
                originalname: residential
                displayname: keys.building.residential
                osmwiki: Tag:building=residential
            church:
                originalkey: building
                originalname: church
                displayname: keys.building.church
                osmwiki: Tag:building=church
                wikidata: Q605315
                wikipedia: church
            mosque:
                originalkey: building
                originalname: mosque
                displayname: keys.building.mosque
                osmwiki: Tag:building=mosque
                wikipedia: Mosque
                wikidata: Q32815
            houseboat:
                originalkey: building
                originalname: houseboat
                displayname: keys.building.houseboat
                osmwiki: Tag:building=houseboat
                wikipedia: Houseboat
                wikidata: Q1321309
            civic:
                originalkey: building
                originalname: civic
                displayname: keys.building.civic
                osmwiki: Tag:building=civic
                wikipedia: Civic_center
                wikidata: Q6583066
            office:
                originalkey: building
                originalname: office
                displayname: keys.building.office
                osmwiki: Tag:building=office
                wikipedia: Office
                wikidata: Q182060
            university:
                originalkey: building
                originalname: university
                displayname: keys.building.university
                osmwiki: Tag:building=university
                wikipedia: University
                wikidata: Q3918
            school:
                originalkey: building
                originalname: school
                displayname: keys.building.school
                osmwiki: Tag:building=school
                wikipedia: School
                wikidata: Q3914
            train_station:
                originalkey: building
                originalname: train_station
                displayname: keys.building.train_station
                osmwiki: Tag:building=train_station
                wikipedia: Train_station
                wikidata: Q55488
    architecture_style:
        displayname: keys.building:architecture.architecture
        wikidata: Q32880
        wikiproperty: P149
        osmwiki: Key:building:architecture
        wikipedia: Architectural_style
        weight: 50
        values:
            art_deco:
                displayname: keys.building:architecture.art_deco
                wikipedia: Art_Deco#Architecture
                wikidata: Q173782
                osmwiki: Key:building:architecture
            art_nouveau:
                displayname: keys.building:architecture.art_nouveau
                wikipedia: Art_Nouveau
                wikidata: Q34636
                osmwiki: Key:building:architecture
            gothic:
                displayname: keys.building:architecture.gothic
                wikipedia: Gothic_architecture
                wikidata: Q176483
                osmwiki: Key:building:architecture
            neo_gothic:
                displayname: keys.building:architecture.neo_gothic
                wikipedia: Gothic_Revival_architecture
                wikidata: Q186363
                osmwiki: Key:building:architecture
            indian:
                displayname: keys.building:architecture.indian
                wikipedia: Indo-Islamic_architecture
                wikidata: Q825394
                osmwiki: Key:building:architecture
            eclectic:
                displayname: keys.building:architecture.eclectic
                wikipedia: Eclecticism_in_architecture
                wikidata: Q2479493
                osmwiki: Key:building:architecture
            modernism:
                displayname: keys.building:architecture.modernism
                wikipedia: Modern_architecture
                wikidata: Q245188
                osmwiki: Key:building:architecture
            classic_swahili:
                displayname: keys.building:architecture.classic_swahili
                wikipedia: Swahili_architecture
                wikidata: Q7652972
                osmwiki: Key:building:architecture
            stone_town:
                displayname: keys.building:architecture.stone_town
                wikipedia: Swahili_architecture
                wikidata: Q7652972
                osmwiki: Key:building:architecture
            british_colonial:
                displayname: keys.building:architecture.british_colonial
                wikipedia: Colonial_architecture#British_colonial_architecture
                wikidata: Q21027192
                osmwiki: Key:building:architecture
            omani:
                displayname: keys.building:architecture.omani
                wikipedia: Oman
                wikidata: Q842
                osmwiki: Key:building:architecture
            omani:
                displayname: keys.building:architecture.omani
                wikipedia: Oman
                wikidata: Q842
                osmwiki: Key:building:architecture
            rijnllandse_gothic:
                displayname: keys.building:architecture.rijnllandse_gothic
                wikipedia: nl:Nederrijnse_gotiek
                wikidata: Q4530145
                osmwiki: Key:building:architecture
    architecture_typology:
        displayname: keys.building:architecture:typology.typology
        wikidata: Q784969
        osmwiki: Key:building:architecture:typology
        wikipedia: Typology_(urban_planning_and_architecture)
        weight: 55
        values:
            single_storey_swahili:
                displayname: keys.building:architecture:typology.single_storey_swahili
            apartment_block:
                displayname: keys.building:architecture:typology.apartment_block
            indian_shopfront:
                displayname: keys.building:architecture:typology.indian_shopfront
            government:
                displayname: keys.building:architecture:typology.government
